#!/usr/bin/env sh
# Copyright 2017 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PAYLOAD=$(mktemp /tmp/resource-check.XXXXXX)

cat > "${PAYLOAD}" <&0

TS=$(jq '.version.timestamp // empty' < "${PAYLOAD}")

if [ -z "${TS}" ]; then
  echo '[]' >&3
else
  jq -n "[
    { timestamp: ${TS} }
  ]" >&3
fi
